server:
  port: 12345

spring:
  application:
    name: yuetong-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: yuetong-gateway
        metadata:
          heart-beat-interval: 5000
          heart-beat-timeout: 20000
          register-enabled: true
          namespace: dev
          cluster-name: Cluster-A
          group: myGroup
    gateway:
      routes:
        - id: "test-producer-impl"
          uri: lb://test-producer-impl
          predicates:
            - Path=/producer/**
        - id: "test-consumer-impl"
          uri: lb://test-consumer-impl
          predicates:
            - Path=/consumer/**
        - id: "yuetong-common-auth"
          uri: lb://yuetong-common-auth
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
