version: "3"

services:
  yuetong_mysql:
    image: mysql:8
    container_name: yuetong_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 6JFNrWBylDPVlRDp #设置root帐号密码
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql #数据文件挂载
      - ./mysql/conf:/etc/mysql/conf.d #配置文件挂载
      - ./mysql/log:/var/log/mysql #日志文件挂载

  yuetong_redis:
    image: redis:7
    container_name: yuetong_redis
    command: redis-server --appendonly yes --requirepass 6JFNrWBylDPVlRDp
    volumes:
      - ./redis/data:/data #数据文件挂载
    ports:
      - "6379:6379"

  yuetong_nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: yuetong_nacos
    environment:
      - "MODE=standalone"
    volumes:
      - ./nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

