server:
  port: 10500
  error:
    include-message: always
spring:
  application:
    name: test-consumer-impl
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: test-consumer-impl
        metadata:
          heart-beat-interval: 5000
          heart-beat-timeout: 20000
          register-enabled: true
          namespace: dev
          cluster-name: Cluster-A
          group: myGroup

logging:
  level:
    cn.tdsmy.consumer: debug