server:
  port: 11010
  error:
    include-message: always
spring:
  application:
    name: yuetong-system-impl
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yuetong
    username: Raymond
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        # 服务注册地址（可配置多个，用逗号分隔）
        server-addr: 127.0.0.1:8848
        # 服务名称（可以不配）
        service: yuetong-system-impl
        metadata:
          # 心跳发送间隔（单位ms）
          heart-beat-interval: 5000
          # 没有收到心跳多长时间后将本服务设为不健康（默认15s）
          heart-beat-timeout: 20000
          register-enabled: true
          namespace: dev
          cluster-name: Cluster-A
          group: myGroup

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: cn/tdsmy/system/beans;
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.tdsmy.system: debug